- name: "upload template {{cloudformation_stack}}"
  s3:
    bucket: "{{cloudformation_bucket}}-{{cloudformation_region}}"
    mode: "put"
    object: "/{{cloudformation_stack}}-{{cloudformation_template|basename}}"
    src: "{{cloudformation_template}}"
    region: "{{cloudformation_region}}"
  when: blok_anan_state == "present" or blok_anan_state == "uploaded"
- name: "create stack {{cloudformation_stack}}"
  cloudformation:
    disable_rollback: "{{cloudformation_disable_rollback}}"
    region: "{{cloudformation_region}}"
    stack_name: "{{cloudformation_stack}}"
    state: "present"
    template: "{{cloudformation_template}}"
    template_parameters: "{{cloudformation_parameters}}"
  when: blok_anan_state == "present"
- name: "delete stack {{cloudformation_stack}}"
  cloudformation:
    region: "{{cloudformation_region}}"
    stack_name: "{{cloudformation_stack}}"
    state: "absent"
    template: "{{cloudformation_template}}"
  when: blok_anan_state == "absent"
